# Generated by Django 4.0.3 on 2022-03-31 03:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address', regex=re.compile('([\\dA-Fa-f]{2})-([\\dA-Fa-f]{2})-([\\dA-Fa-f]{2})-([\\dA-Fa-f]{2})-([\\dA-Fa-f]{2})-([\\dA-Fa-f]{2})'))])),
                ('pet_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.SlugField(unique=True)),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.DateTimeField(verbose_name='Time Received')),
                ('time_published', models.TimeField(verbose_name='Time Published')),
                ('pushed_to_server', models.BooleanField(default=False)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pawfig.beacon')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pawfig.device', to_field='serial_num')),
            ],
        ),
    ]
